name: Push Laravel Images To DockerHub Then Deploy to EC2 Production

on:
  push:
    branches:
      - Production

jobs:
  Build-Laravel-And-Push-Dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Laravel Docker image
        working-directory: php-gitflow-automation
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/gitflow_automation_laravel:20 .

      - name: Push Laravel Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/gitflow_automation_laravel:20

  Copy-docker-compose-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose to EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "docker-compose.yaml"
          target: "/home/${{ secrets.EC2_USER }}/"

  Deploy-To-EC2:
    needs:
      [
        Build-Laravel-And-Push-Dockerhub,
        Copy-docker-compose-To-EC2,
      ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/gitflow_automation_laravel:20           
            docker compose up -d